title: Kelvin Liusiani # your name (or website title) here
logo: "/images/kelvin.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  <br>
  <b style="font-size:25px">Contact Me</b>
  <br>
  &nbsp;&nbsp;<a href="mailto: kelvinliu04@gmail.com target="_blank"" title="Hi, Kelvin!">Email</a> 
  <br>
  &nbsp;&nbsp;<a href="https://github.com/kelvinliu04">GitHub Profile</a> 
  <br>
  &nbsp;&nbsp;<a href="https://www.linkedin.com/in/kelvin-liusiani/">LinkedIn Profile</a> 
  <br>
  &nbsp;&nbsp;<a href="https://github.com/kelvinliu04/kelvinliu04.github.io/blob/master/images/resume.pdf">Resume / CV</a> 
  <br>
  <br>
  <b style="font-size:25px">Portfolio</b>
  <br>
  &nbsp;&nbsp;<a href="/computervision">Computer Vision</a> 
  <br>
  &nbsp;&nbsp;<a href="/ml">Machine Learning</a> 
  <br>
  &nbsp;&nbsp;<a href="/iot">Robotics/Iot</a> 

  
markdown: kramdown
theme: jekyll-theme-minimal

