title: Kelvin Liusiani # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b style="font-size:23px">Contact Me</b>
  <br>
  &nbsp;&nbsp;<a href="https://github.com/kelvinliu04">GitHub Profile</a> 
  <br>
  <a href="https://www.linkedin.com/in/kelvin-liusiani/">LinkedIn Profile</a> 
  
  <b style="font-size:23px">Menu</b>
  
  
theme: jekyll-theme-minimal

